repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-toml
      - id: check-yaml
      - id: end-of-file-fixer
      - id: mixed-line-ending
        args: [ --fix=no ]
      - id: trailing-whitespace
        args: [ --markdown-linebreak-ext=md ]
-   repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.32.2
    hooks:
      - id: markdownlint-fix
-   repo: https://github.com/crate-ci/typos
    rev: v1.12.14
    hooks:
      - id: typos
-   repo: https://github.com/thibaudcolas/pre-commit-stylelint
    rev: v14.4.0
    hooks:
      - id: stylelint
        additional_dependencies:
          # stylelint itself needs to be here when using additional_dependencies.
          - stylelint@14.4.0
          - stylelint-config-standard-scss@3.0.0
